
interface _GlobalComponents {
      'CommonCabecalhoSistema': typeof import("../components/common/CabecalhoSistema.vue")['default']
    'CommonInfoTooltip': typeof import("../components/common/InfoTooltip.vue")['default']
    'CommonMenuPrincipal': typeof import("../components/common/MenuPrincipal.vue")['default']
    'CommonSplashScreen': typeof import("../components/common/SplashScreen.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'PrimeAutoComplete': typeof import("primevue/autocomplete")['default']
    'PrimeCalendar': typeof import("primevue/calendar")['default']
    'PrimeCascadeSelect': typeof import("primevue/cascadeselect")['default']
    'PrimeCheckbox': typeof import("primevue/checkbox")['default']
    'PrimeChips': typeof import("primevue/chips")['default']
    'PrimeColorPicker': typeof import("primevue/colorpicker")['default']
    'PrimeDropdown': typeof import("primevue/dropdown")['default']
    'PrimeFloatLabel': typeof import("primevue/floatlabel")['default']
    'PrimeIconField': typeof import("primevue/iconfield")['default']
    'PrimeInputGroup': typeof import("primevue/inputgroup")['default']
    'PrimeInputGroupAddon': typeof import("primevue/inputgroupaddon")['default']
    'PrimeInputIcon': typeof import("primevue/inputicon")['default']
    'PrimeInputMask': typeof import("primevue/inputmask")['default']
    'PrimeInputNumber': typeof import("primevue/inputnumber")['default']
    'PrimeInputOtp': typeof import("primevue/inputotp")['default']
    'PrimeInputSwitch': typeof import("primevue/inputswitch")['default']
    'PrimeInputText': typeof import("primevue/inputtext")['default']
    'PrimeKnob': typeof import("primevue/knob")['default']
    'PrimeListbox': typeof import("primevue/listbox")['default']
    'PrimeMultiSelect': typeof import("primevue/multiselect")['default']
    'PrimePassword': typeof import("primevue/password")['default']
    'PrimeRadioButton': typeof import("primevue/radiobutton")['default']
    'PrimeRating': typeof import("primevue/rating")['default']
    'PrimeSelectButton': typeof import("primevue/selectbutton")['default']
    'PrimeSlider': typeof import("primevue/slider")['default']
    'PrimeTextarea': typeof import("primevue/textarea")['default']
    'PrimeToggleButton': typeof import("primevue/togglebutton")['default']
    'PrimeTreeSelect': typeof import("primevue/treeselect")['default']
    'PrimeTriStateCheckbox': typeof import("primevue/tristatecheckbox")['default']
    'PrimeButton': typeof import("primevue/button")['default']
    'PrimeButtonGroup': typeof import("primevue/buttongroup")['default']
    'PrimeSpeedDial': typeof import("primevue/speeddial")['default']
    'PrimeSplitButton': typeof import("primevue/splitbutton")['default']
    'PrimeColumn': typeof import("primevue/column")['default']
    'PrimeRow': typeof import("primevue/row")['default']
    'PrimeColumnGroup': typeof import("primevue/columngroup")['default']
    'PrimeDataTable': typeof import("primevue/datatable")['default']
    'PrimeDataView': typeof import("primevue/dataview")['default']
    'PrimeDataViewLayoutOptions': typeof import("primevue/dataviewlayoutoptions")['default']
    'PrimeOrderList': typeof import("primevue/orderlist")['default']
    'PrimeOrganizationChart': typeof import("primevue/organizationchart")['default']
    'PrimePaginator': typeof import("primevue/paginator")['default']
    'PrimePickList': typeof import("primevue/picklist")['default']
    'PrimeTree': typeof import("primevue/tree")['default']
    'PrimeTreeTable': typeof import("primevue/treetable")['default']
    'PrimeTimeline': typeof import("primevue/timeline")['default']
    'PrimeVirtualScroller': typeof import("primevue/virtualscroller")['default']
    'PrimeAccordion': typeof import("primevue/accordion")['default']
    'PrimeAccordionTab': typeof import("primevue/accordiontab")['default']
    'PrimeCard': typeof import("primevue/card")['default']
    'PrimeDeferredContent': typeof import("primevue/deferredcontent")['default']
    'PrimeDivider': typeof import("primevue/divider")['default']
    'PrimeFieldset': typeof import("primevue/fieldset")['default']
    'PrimePanel': typeof import("primevue/panel")['default']
    'PrimeScrollPanel': typeof import("primevue/scrollpanel")['default']
    'PrimeSplitter': typeof import("primevue/splitter")['default']
    'PrimeSplitterPanel': typeof import("primevue/splitterpanel")['default']
    'PrimeStepper': typeof import("primevue/stepper")['default']
    'PrimeStepperPanel': typeof import("primevue/stepperpanel")['default']
    'PrimeTabView': typeof import("primevue/tabview")['default']
    'PrimeTabPanel': typeof import("primevue/tabpanel")['default']
    'PrimeToolbar': typeof import("primevue/toolbar")['default']
    'PrimeConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'PrimeConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'PrimeDialog': typeof import("primevue/dialog")['default']
    'PrimeDynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'PrimeOverlayPanel': typeof import("primevue/overlaypanel")['default']
    'PrimeSidebar': typeof import("primevue/sidebar")['default']
    'PrimeFileUpload': typeof import("primevue/fileupload")['default']
    'PrimeBreadcrumb': typeof import("primevue/breadcrumb")['default']
    'PrimeContextMenu': typeof import("primevue/contextmenu")['default']
    'PrimeDock': typeof import("primevue/dock")['default']
    'PrimeMenu': typeof import("primevue/menu")['default']
    'PrimeMenubar': typeof import("primevue/menubar")['default']
    'PrimeMegaMenu': typeof import("primevue/megamenu")['default']
    'PrimePanelMenu': typeof import("primevue/panelmenu")['default']
    'PrimeSteps': typeof import("primevue/steps")['default']
    'PrimeTabMenu': typeof import("primevue/tabmenu")['default']
    'PrimeTieredMenu': typeof import("primevue/tieredmenu")['default']
    'PrimeChart': typeof import("primevue/chart")['default']
    'PrimeMessage': typeof import("primevue/message")['default']
    'PrimeInlineMessage': typeof import("primevue/inlinemessage")['default']
    'PrimeToast': typeof import("primevue/toast")['default']
    'PrimeCarousel': typeof import("primevue/carousel")['default']
    'PrimeGalleria': typeof import("primevue/galleria")['default']
    'PrimeImage': typeof import("primevue/image")['default']
    'PrimeAvatar': typeof import("primevue/avatar")['default']
    'PrimeAvatarGroup': typeof import("primevue/avatargroup")['default']
    'PrimeBadge': typeof import("primevue/badge")['default']
    'PrimeBlockUI': typeof import("primevue/blockui")['default']
    'PrimeChip': typeof import("primevue/chip")['default']
    'PrimeInplace': typeof import("primevue/inplace")['default']
    'PrimeMeterGroup': typeof import("primevue/metergroup")['default']
    'PrimeScrollTop': typeof import("primevue/scrolltop")['default']
    'PrimeSkeleton': typeof import("primevue/skeleton")['default']
    'PrimeProgressBar': typeof import("primevue/progressbar")['default']
    'PrimeProgressSpinner': typeof import("primevue/progressspinner")['default']
    'PrimeTag': typeof import("primevue/tag")['default']
    'PrimeTerminal': typeof import("primevue/terminal")['default']
    'Field': typeof import("vee-validate")['Field']
    'Form': typeof import("vee-validate")['Form']
    'ErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'FieldArray': typeof import("vee-validate")['FieldArray']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyCommonCabecalhoSistema': typeof import("../components/common/CabecalhoSistema.vue")['default']
    'LazyCommonInfoTooltip': typeof import("../components/common/InfoTooltip.vue")['default']
    'LazyCommonMenuPrincipal': typeof import("../components/common/MenuPrincipal.vue")['default']
    'LazyCommonSplashScreen': typeof import("../components/common/SplashScreen.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyPrimeAutoComplete': typeof import("primevue/autocomplete")['default']
    'LazyPrimeCalendar': typeof import("primevue/calendar")['default']
    'LazyPrimeCascadeSelect': typeof import("primevue/cascadeselect")['default']
    'LazyPrimeCheckbox': typeof import("primevue/checkbox")['default']
    'LazyPrimeChips': typeof import("primevue/chips")['default']
    'LazyPrimeColorPicker': typeof import("primevue/colorpicker")['default']
    'LazyPrimeDropdown': typeof import("primevue/dropdown")['default']
    'LazyPrimeFloatLabel': typeof import("primevue/floatlabel")['default']
    'LazyPrimeIconField': typeof import("primevue/iconfield")['default']
    'LazyPrimeInputGroup': typeof import("primevue/inputgroup")['default']
    'LazyPrimeInputGroupAddon': typeof import("primevue/inputgroupaddon")['default']
    'LazyPrimeInputIcon': typeof import("primevue/inputicon")['default']
    'LazyPrimeInputMask': typeof import("primevue/inputmask")['default']
    'LazyPrimeInputNumber': typeof import("primevue/inputnumber")['default']
    'LazyPrimeInputOtp': typeof import("primevue/inputotp")['default']
    'LazyPrimeInputSwitch': typeof import("primevue/inputswitch")['default']
    'LazyPrimeInputText': typeof import("primevue/inputtext")['default']
    'LazyPrimeKnob': typeof import("primevue/knob")['default']
    'LazyPrimeListbox': typeof import("primevue/listbox")['default']
    'LazyPrimeMultiSelect': typeof import("primevue/multiselect")['default']
    'LazyPrimePassword': typeof import("primevue/password")['default']
    'LazyPrimeRadioButton': typeof import("primevue/radiobutton")['default']
    'LazyPrimeRating': typeof import("primevue/rating")['default']
    'LazyPrimeSelectButton': typeof import("primevue/selectbutton")['default']
    'LazyPrimeSlider': typeof import("primevue/slider")['default']
    'LazyPrimeTextarea': typeof import("primevue/textarea")['default']
    'LazyPrimeToggleButton': typeof import("primevue/togglebutton")['default']
    'LazyPrimeTreeSelect': typeof import("primevue/treeselect")['default']
    'LazyPrimeTriStateCheckbox': typeof import("primevue/tristatecheckbox")['default']
    'LazyPrimeButton': typeof import("primevue/button")['default']
    'LazyPrimeButtonGroup': typeof import("primevue/buttongroup")['default']
    'LazyPrimeSpeedDial': typeof import("primevue/speeddial")['default']
    'LazyPrimeSplitButton': typeof import("primevue/splitbutton")['default']
    'LazyPrimeColumn': typeof import("primevue/column")['default']
    'LazyPrimeRow': typeof import("primevue/row")['default']
    'LazyPrimeColumnGroup': typeof import("primevue/columngroup")['default']
    'LazyPrimeDataTable': typeof import("primevue/datatable")['default']
    'LazyPrimeDataView': typeof import("primevue/dataview")['default']
    'LazyPrimeDataViewLayoutOptions': typeof import("primevue/dataviewlayoutoptions")['default']
    'LazyPrimeOrderList': typeof import("primevue/orderlist")['default']
    'LazyPrimeOrganizationChart': typeof import("primevue/organizationchart")['default']
    'LazyPrimePaginator': typeof import("primevue/paginator")['default']
    'LazyPrimePickList': typeof import("primevue/picklist")['default']
    'LazyPrimeTree': typeof import("primevue/tree")['default']
    'LazyPrimeTreeTable': typeof import("primevue/treetable")['default']
    'LazyPrimeTimeline': typeof import("primevue/timeline")['default']
    'LazyPrimeVirtualScroller': typeof import("primevue/virtualscroller")['default']
    'LazyPrimeAccordion': typeof import("primevue/accordion")['default']
    'LazyPrimeAccordionTab': typeof import("primevue/accordiontab")['default']
    'LazyPrimeCard': typeof import("primevue/card")['default']
    'LazyPrimeDeferredContent': typeof import("primevue/deferredcontent")['default']
    'LazyPrimeDivider': typeof import("primevue/divider")['default']
    'LazyPrimeFieldset': typeof import("primevue/fieldset")['default']
    'LazyPrimePanel': typeof import("primevue/panel")['default']
    'LazyPrimeScrollPanel': typeof import("primevue/scrollpanel")['default']
    'LazyPrimeSplitter': typeof import("primevue/splitter")['default']
    'LazyPrimeSplitterPanel': typeof import("primevue/splitterpanel")['default']
    'LazyPrimeStepper': typeof import("primevue/stepper")['default']
    'LazyPrimeStepperPanel': typeof import("primevue/stepperpanel")['default']
    'LazyPrimeTabView': typeof import("primevue/tabview")['default']
    'LazyPrimeTabPanel': typeof import("primevue/tabpanel")['default']
    'LazyPrimeToolbar': typeof import("primevue/toolbar")['default']
    'LazyPrimeConfirmDialog': typeof import("primevue/confirmdialog")['default']
    'LazyPrimeConfirmPopup': typeof import("primevue/confirmpopup")['default']
    'LazyPrimeDialog': typeof import("primevue/dialog")['default']
    'LazyPrimeDynamicDialog': typeof import("primevue/dynamicdialog")['default']
    'LazyPrimeOverlayPanel': typeof import("primevue/overlaypanel")['default']
    'LazyPrimeSidebar': typeof import("primevue/sidebar")['default']
    'LazyPrimeFileUpload': typeof import("primevue/fileupload")['default']
    'LazyPrimeBreadcrumb': typeof import("primevue/breadcrumb")['default']
    'LazyPrimeContextMenu': typeof import("primevue/contextmenu")['default']
    'LazyPrimeDock': typeof import("primevue/dock")['default']
    'LazyPrimeMenu': typeof import("primevue/menu")['default']
    'LazyPrimeMenubar': typeof import("primevue/menubar")['default']
    'LazyPrimeMegaMenu': typeof import("primevue/megamenu")['default']
    'LazyPrimePanelMenu': typeof import("primevue/panelmenu")['default']
    'LazyPrimeSteps': typeof import("primevue/steps")['default']
    'LazyPrimeTabMenu': typeof import("primevue/tabmenu")['default']
    'LazyPrimeTieredMenu': typeof import("primevue/tieredmenu")['default']
    'LazyPrimeChart': typeof import("primevue/chart")['default']
    'LazyPrimeMessage': typeof import("primevue/message")['default']
    'LazyPrimeInlineMessage': typeof import("primevue/inlinemessage")['default']
    'LazyPrimeToast': typeof import("primevue/toast")['default']
    'LazyPrimeCarousel': typeof import("primevue/carousel")['default']
    'LazyPrimeGalleria': typeof import("primevue/galleria")['default']
    'LazyPrimeImage': typeof import("primevue/image")['default']
    'LazyPrimeAvatar': typeof import("primevue/avatar")['default']
    'LazyPrimeAvatarGroup': typeof import("primevue/avatargroup")['default']
    'LazyPrimeBadge': typeof import("primevue/badge")['default']
    'LazyPrimeBlockUI': typeof import("primevue/blockui")['default']
    'LazyPrimeChip': typeof import("primevue/chip")['default']
    'LazyPrimeInplace': typeof import("primevue/inplace")['default']
    'LazyPrimeMeterGroup': typeof import("primevue/metergroup")['default']
    'LazyPrimeScrollTop': typeof import("primevue/scrolltop")['default']
    'LazyPrimeSkeleton': typeof import("primevue/skeleton")['default']
    'LazyPrimeProgressBar': typeof import("primevue/progressbar")['default']
    'LazyPrimeProgressSpinner': typeof import("primevue/progressspinner")['default']
    'LazyPrimeTag': typeof import("primevue/tag")['default']
    'LazyPrimeTerminal': typeof import("primevue/terminal")['default']
    'LazyField': typeof import("vee-validate")['Field']
    'LazyForm': typeof import("vee-validate")['Form']
    'LazyErrorMessage': typeof import("vee-validate")['ErrorMessage']
    'LazyFieldArray': typeof import("vee-validate")['FieldArray']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CommonCabecalhoSistema: typeof import("../components/common/CabecalhoSistema.vue")['default']
export const CommonInfoTooltip: typeof import("../components/common/InfoTooltip.vue")['default']
export const CommonMenuPrincipal: typeof import("../components/common/MenuPrincipal.vue")['default']
export const CommonSplashScreen: typeof import("../components/common/SplashScreen.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const PrimeAutoComplete: typeof import("primevue/autocomplete")['default']
export const PrimeCalendar: typeof import("primevue/calendar")['default']
export const PrimeCascadeSelect: typeof import("primevue/cascadeselect")['default']
export const PrimeCheckbox: typeof import("primevue/checkbox")['default']
export const PrimeChips: typeof import("primevue/chips")['default']
export const PrimeColorPicker: typeof import("primevue/colorpicker")['default']
export const PrimeDropdown: typeof import("primevue/dropdown")['default']
export const PrimeFloatLabel: typeof import("primevue/floatlabel")['default']
export const PrimeIconField: typeof import("primevue/iconfield")['default']
export const PrimeInputGroup: typeof import("primevue/inputgroup")['default']
export const PrimeInputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const PrimeInputIcon: typeof import("primevue/inputicon")['default']
export const PrimeInputMask: typeof import("primevue/inputmask")['default']
export const PrimeInputNumber: typeof import("primevue/inputnumber")['default']
export const PrimeInputOtp: typeof import("primevue/inputotp")['default']
export const PrimeInputSwitch: typeof import("primevue/inputswitch")['default']
export const PrimeInputText: typeof import("primevue/inputtext")['default']
export const PrimeKnob: typeof import("primevue/knob")['default']
export const PrimeListbox: typeof import("primevue/listbox")['default']
export const PrimeMultiSelect: typeof import("primevue/multiselect")['default']
export const PrimePassword: typeof import("primevue/password")['default']
export const PrimeRadioButton: typeof import("primevue/radiobutton")['default']
export const PrimeRating: typeof import("primevue/rating")['default']
export const PrimeSelectButton: typeof import("primevue/selectbutton")['default']
export const PrimeSlider: typeof import("primevue/slider")['default']
export const PrimeTextarea: typeof import("primevue/textarea")['default']
export const PrimeToggleButton: typeof import("primevue/togglebutton")['default']
export const PrimeTreeSelect: typeof import("primevue/treeselect")['default']
export const PrimeTriStateCheckbox: typeof import("primevue/tristatecheckbox")['default']
export const PrimeButton: typeof import("primevue/button")['default']
export const PrimeButtonGroup: typeof import("primevue/buttongroup")['default']
export const PrimeSpeedDial: typeof import("primevue/speeddial")['default']
export const PrimeSplitButton: typeof import("primevue/splitbutton")['default']
export const PrimeColumn: typeof import("primevue/column")['default']
export const PrimeRow: typeof import("primevue/row")['default']
export const PrimeColumnGroup: typeof import("primevue/columngroup")['default']
export const PrimeDataTable: typeof import("primevue/datatable")['default']
export const PrimeDataView: typeof import("primevue/dataview")['default']
export const PrimeDataViewLayoutOptions: typeof import("primevue/dataviewlayoutoptions")['default']
export const PrimeOrderList: typeof import("primevue/orderlist")['default']
export const PrimeOrganizationChart: typeof import("primevue/organizationchart")['default']
export const PrimePaginator: typeof import("primevue/paginator")['default']
export const PrimePickList: typeof import("primevue/picklist")['default']
export const PrimeTree: typeof import("primevue/tree")['default']
export const PrimeTreeTable: typeof import("primevue/treetable")['default']
export const PrimeTimeline: typeof import("primevue/timeline")['default']
export const PrimeVirtualScroller: typeof import("primevue/virtualscroller")['default']
export const PrimeAccordion: typeof import("primevue/accordion")['default']
export const PrimeAccordionTab: typeof import("primevue/accordiontab")['default']
export const PrimeCard: typeof import("primevue/card")['default']
export const PrimeDeferredContent: typeof import("primevue/deferredcontent")['default']
export const PrimeDivider: typeof import("primevue/divider")['default']
export const PrimeFieldset: typeof import("primevue/fieldset")['default']
export const PrimePanel: typeof import("primevue/panel")['default']
export const PrimeScrollPanel: typeof import("primevue/scrollpanel")['default']
export const PrimeSplitter: typeof import("primevue/splitter")['default']
export const PrimeSplitterPanel: typeof import("primevue/splitterpanel")['default']
export const PrimeStepper: typeof import("primevue/stepper")['default']
export const PrimeStepperPanel: typeof import("primevue/stepperpanel")['default']
export const PrimeTabView: typeof import("primevue/tabview")['default']
export const PrimeTabPanel: typeof import("primevue/tabpanel")['default']
export const PrimeToolbar: typeof import("primevue/toolbar")['default']
export const PrimeConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const PrimeConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const PrimeDialog: typeof import("primevue/dialog")['default']
export const PrimeDynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const PrimeOverlayPanel: typeof import("primevue/overlaypanel")['default']
export const PrimeSidebar: typeof import("primevue/sidebar")['default']
export const PrimeFileUpload: typeof import("primevue/fileupload")['default']
export const PrimeBreadcrumb: typeof import("primevue/breadcrumb")['default']
export const PrimeContextMenu: typeof import("primevue/contextmenu")['default']
export const PrimeDock: typeof import("primevue/dock")['default']
export const PrimeMenu: typeof import("primevue/menu")['default']
export const PrimeMenubar: typeof import("primevue/menubar")['default']
export const PrimeMegaMenu: typeof import("primevue/megamenu")['default']
export const PrimePanelMenu: typeof import("primevue/panelmenu")['default']
export const PrimeSteps: typeof import("primevue/steps")['default']
export const PrimeTabMenu: typeof import("primevue/tabmenu")['default']
export const PrimeTieredMenu: typeof import("primevue/tieredmenu")['default']
export const PrimeChart: typeof import("primevue/chart")['default']
export const PrimeMessage: typeof import("primevue/message")['default']
export const PrimeInlineMessage: typeof import("primevue/inlinemessage")['default']
export const PrimeToast: typeof import("primevue/toast")['default']
export const PrimeCarousel: typeof import("primevue/carousel")['default']
export const PrimeGalleria: typeof import("primevue/galleria")['default']
export const PrimeImage: typeof import("primevue/image")['default']
export const PrimeAvatar: typeof import("primevue/avatar")['default']
export const PrimeAvatarGroup: typeof import("primevue/avatargroup")['default']
export const PrimeBadge: typeof import("primevue/badge")['default']
export const PrimeBlockUI: typeof import("primevue/blockui")['default']
export const PrimeChip: typeof import("primevue/chip")['default']
export const PrimeInplace: typeof import("primevue/inplace")['default']
export const PrimeMeterGroup: typeof import("primevue/metergroup")['default']
export const PrimeScrollTop: typeof import("primevue/scrolltop")['default']
export const PrimeSkeleton: typeof import("primevue/skeleton")['default']
export const PrimeProgressBar: typeof import("primevue/progressbar")['default']
export const PrimeProgressSpinner: typeof import("primevue/progressspinner")['default']
export const PrimeTag: typeof import("primevue/tag")['default']
export const PrimeTerminal: typeof import("primevue/terminal")['default']
export const Field: typeof import("vee-validate")['Field']
export const Form: typeof import("vee-validate")['Form']
export const ErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const FieldArray: typeof import("vee-validate")['FieldArray']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyCommonCabecalhoSistema: typeof import("../components/common/CabecalhoSistema.vue")['default']
export const LazyCommonInfoTooltip: typeof import("../components/common/InfoTooltip.vue")['default']
export const LazyCommonMenuPrincipal: typeof import("../components/common/MenuPrincipal.vue")['default']
export const LazyCommonSplashScreen: typeof import("../components/common/SplashScreen.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyPrimeAutoComplete: typeof import("primevue/autocomplete")['default']
export const LazyPrimeCalendar: typeof import("primevue/calendar")['default']
export const LazyPrimeCascadeSelect: typeof import("primevue/cascadeselect")['default']
export const LazyPrimeCheckbox: typeof import("primevue/checkbox")['default']
export const LazyPrimeChips: typeof import("primevue/chips")['default']
export const LazyPrimeColorPicker: typeof import("primevue/colorpicker")['default']
export const LazyPrimeDropdown: typeof import("primevue/dropdown")['default']
export const LazyPrimeFloatLabel: typeof import("primevue/floatlabel")['default']
export const LazyPrimeIconField: typeof import("primevue/iconfield")['default']
export const LazyPrimeInputGroup: typeof import("primevue/inputgroup")['default']
export const LazyPrimeInputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
export const LazyPrimeInputIcon: typeof import("primevue/inputicon")['default']
export const LazyPrimeInputMask: typeof import("primevue/inputmask")['default']
export const LazyPrimeInputNumber: typeof import("primevue/inputnumber")['default']
export const LazyPrimeInputOtp: typeof import("primevue/inputotp")['default']
export const LazyPrimeInputSwitch: typeof import("primevue/inputswitch")['default']
export const LazyPrimeInputText: typeof import("primevue/inputtext")['default']
export const LazyPrimeKnob: typeof import("primevue/knob")['default']
export const LazyPrimeListbox: typeof import("primevue/listbox")['default']
export const LazyPrimeMultiSelect: typeof import("primevue/multiselect")['default']
export const LazyPrimePassword: typeof import("primevue/password")['default']
export const LazyPrimeRadioButton: typeof import("primevue/radiobutton")['default']
export const LazyPrimeRating: typeof import("primevue/rating")['default']
export const LazyPrimeSelectButton: typeof import("primevue/selectbutton")['default']
export const LazyPrimeSlider: typeof import("primevue/slider")['default']
export const LazyPrimeTextarea: typeof import("primevue/textarea")['default']
export const LazyPrimeToggleButton: typeof import("primevue/togglebutton")['default']
export const LazyPrimeTreeSelect: typeof import("primevue/treeselect")['default']
export const LazyPrimeTriStateCheckbox: typeof import("primevue/tristatecheckbox")['default']
export const LazyPrimeButton: typeof import("primevue/button")['default']
export const LazyPrimeButtonGroup: typeof import("primevue/buttongroup")['default']
export const LazyPrimeSpeedDial: typeof import("primevue/speeddial")['default']
export const LazyPrimeSplitButton: typeof import("primevue/splitbutton")['default']
export const LazyPrimeColumn: typeof import("primevue/column")['default']
export const LazyPrimeRow: typeof import("primevue/row")['default']
export const LazyPrimeColumnGroup: typeof import("primevue/columngroup")['default']
export const LazyPrimeDataTable: typeof import("primevue/datatable")['default']
export const LazyPrimeDataView: typeof import("primevue/dataview")['default']
export const LazyPrimeDataViewLayoutOptions: typeof import("primevue/dataviewlayoutoptions")['default']
export const LazyPrimeOrderList: typeof import("primevue/orderlist")['default']
export const LazyPrimeOrganizationChart: typeof import("primevue/organizationchart")['default']
export const LazyPrimePaginator: typeof import("primevue/paginator")['default']
export const LazyPrimePickList: typeof import("primevue/picklist")['default']
export const LazyPrimeTree: typeof import("primevue/tree")['default']
export const LazyPrimeTreeTable: typeof import("primevue/treetable")['default']
export const LazyPrimeTimeline: typeof import("primevue/timeline")['default']
export const LazyPrimeVirtualScroller: typeof import("primevue/virtualscroller")['default']
export const LazyPrimeAccordion: typeof import("primevue/accordion")['default']
export const LazyPrimeAccordionTab: typeof import("primevue/accordiontab")['default']
export const LazyPrimeCard: typeof import("primevue/card")['default']
export const LazyPrimeDeferredContent: typeof import("primevue/deferredcontent")['default']
export const LazyPrimeDivider: typeof import("primevue/divider")['default']
export const LazyPrimeFieldset: typeof import("primevue/fieldset")['default']
export const LazyPrimePanel: typeof import("primevue/panel")['default']
export const LazyPrimeScrollPanel: typeof import("primevue/scrollpanel")['default']
export const LazyPrimeSplitter: typeof import("primevue/splitter")['default']
export const LazyPrimeSplitterPanel: typeof import("primevue/splitterpanel")['default']
export const LazyPrimeStepper: typeof import("primevue/stepper")['default']
export const LazyPrimeStepperPanel: typeof import("primevue/stepperpanel")['default']
export const LazyPrimeTabView: typeof import("primevue/tabview")['default']
export const LazyPrimeTabPanel: typeof import("primevue/tabpanel")['default']
export const LazyPrimeToolbar: typeof import("primevue/toolbar")['default']
export const LazyPrimeConfirmDialog: typeof import("primevue/confirmdialog")['default']
export const LazyPrimeConfirmPopup: typeof import("primevue/confirmpopup")['default']
export const LazyPrimeDialog: typeof import("primevue/dialog")['default']
export const LazyPrimeDynamicDialog: typeof import("primevue/dynamicdialog")['default']
export const LazyPrimeOverlayPanel: typeof import("primevue/overlaypanel")['default']
export const LazyPrimeSidebar: typeof import("primevue/sidebar")['default']
export const LazyPrimeFileUpload: typeof import("primevue/fileupload")['default']
export const LazyPrimeBreadcrumb: typeof import("primevue/breadcrumb")['default']
export const LazyPrimeContextMenu: typeof import("primevue/contextmenu")['default']
export const LazyPrimeDock: typeof import("primevue/dock")['default']
export const LazyPrimeMenu: typeof import("primevue/menu")['default']
export const LazyPrimeMenubar: typeof import("primevue/menubar")['default']
export const LazyPrimeMegaMenu: typeof import("primevue/megamenu")['default']
export const LazyPrimePanelMenu: typeof import("primevue/panelmenu")['default']
export const LazyPrimeSteps: typeof import("primevue/steps")['default']
export const LazyPrimeTabMenu: typeof import("primevue/tabmenu")['default']
export const LazyPrimeTieredMenu: typeof import("primevue/tieredmenu")['default']
export const LazyPrimeChart: typeof import("primevue/chart")['default']
export const LazyPrimeMessage: typeof import("primevue/message")['default']
export const LazyPrimeInlineMessage: typeof import("primevue/inlinemessage")['default']
export const LazyPrimeToast: typeof import("primevue/toast")['default']
export const LazyPrimeCarousel: typeof import("primevue/carousel")['default']
export const LazyPrimeGalleria: typeof import("primevue/galleria")['default']
export const LazyPrimeImage: typeof import("primevue/image")['default']
export const LazyPrimeAvatar: typeof import("primevue/avatar")['default']
export const LazyPrimeAvatarGroup: typeof import("primevue/avatargroup")['default']
export const LazyPrimeBadge: typeof import("primevue/badge")['default']
export const LazyPrimeBlockUI: typeof import("primevue/blockui")['default']
export const LazyPrimeChip: typeof import("primevue/chip")['default']
export const LazyPrimeInplace: typeof import("primevue/inplace")['default']
export const LazyPrimeMeterGroup: typeof import("primevue/metergroup")['default']
export const LazyPrimeScrollTop: typeof import("primevue/scrolltop")['default']
export const LazyPrimeSkeleton: typeof import("primevue/skeleton")['default']
export const LazyPrimeProgressBar: typeof import("primevue/progressbar")['default']
export const LazyPrimeProgressSpinner: typeof import("primevue/progressspinner")['default']
export const LazyPrimeTag: typeof import("primevue/tag")['default']
export const LazyPrimeTerminal: typeof import("primevue/terminal")['default']
export const LazyField: typeof import("vee-validate")['Field']
export const LazyForm: typeof import("vee-validate")['Form']
export const LazyErrorMessage: typeof import("vee-validate")['ErrorMessage']
export const LazyFieldArray: typeof import("vee-validate")['FieldArray']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
